# Generated by Django 3.2.21 on 2023-11-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ManyToManyField(to='core.Subject'),
        ),
    ]
